export const ledgerResult = {
  isDesign: true,
  nodes: [
    {
      id: "ledger",
      name: "Ledger",
      kind: "system",
      grain: "system",
      parentId: null,
      what: "Keeps the household books for this family",
      why: "So the family can see where money goes before they spend it",
    },
    {
      id: "capture",
      name: "Capture",
      kind: "component",
      grain: "component",
      parentId: "ledger",
      what: "Records a purchase the moment someone pays",
      why: "Nothing else in Ledger can explain spending if the purchase was never written down",
    },
    {
      id: "receipts",
      name: "Receipt intake",
      kind: "module",
      grain: "module",
      parentId: "capture",
      what: "Turns a photo of a receipt into a purchase record",
      why: "Capture should not make people type every line when they already have the slip",
    },
    {
      id: "parse-fn",
      name: "parseReceipt()",
      kind: "module",
      grain: "function",
      parentId: "capture",
      what: "Reads the amount off a slip",
      why: "Capture needs the number before it can store the purchase",
    },
    {
      id: "invoice-file",
      name: "invoice.ts",
      kind: "module",
      grain: "file",
      parentId: "capture",
      what: "Holds the purchase type",
      why: "The compiler needs a place for the shape of a purchase",
    },
    {
      id: "charge-class",
      name: "class Charge",
      kind: "module",
      grain: "class",
      parentId: "capture",
      what: "Represents one charge",
      why: "The language wants a type for a charge",
    },
    {
      id: "post-route",
      name: "POST /charges",
      kind: "module",
      grain: "endpoint",
      parentId: "capture",
      what: "Accepts a new charge",
      why: "The client needs an HTTP route",
    },
    {
      id: "call",
      name: "chargeWeekly()",
      kind: "module",
      parentId: "capture",
      what: "Charges the card every week",
      why: "A schedule has to live somewhere in the language",
    },
    {
      id: "source-file",
      name: "src/capture/receipts.ts",
      kind: "module",
      parentId: "capture",
      what: "Stores the receipt reader",
      why: "The build needs a source file for that reader",
    },
    {
      id: "echo",
      name: "Echo",
      kind: "component",
      grain: "component",
      parentId: "ledger",
      what: "Repeats the purchase back to the screen",
      why: "Repeats the purchase back to the screen",
    },
  ],
};

export const weeklyDrift = {
  diverges: true,
  nodeId: "capture",
  intent: "Purchases should be recorded on the day they happen",
  difference: "The code writes the purchase a week later",
};
